User.create(first_name: "Brian", last_name: "Feldman", username: "bf", password: "1")
User.create(first_name: "Arthur", last_name: "Wilton", username: "aw", password: "2")
User.create(first_name: "Bill", last_name: "Ted", username: "bt", password: "3")
User.create(first_name: "George", last_name: "Washington", username: "gw", password: "4")
User.create(first_name: "John", last_name: "Adams", username: "ja", password: "5")
User.create(first_name: "Thomas", last_name: "Jefferson", username: "tj", password: "6")
User.create(first_name: "James", last_name: "Madison", username: "jm", password: "7")
User.create(first_name: "Andrew", last_name: "Jackson", username: "aj", password: "8")



List.create(user_id: 1, name: "Cool Movies")
List.create(user_id: 2, name: "Arthur's movies")
List.create(user_id: 3, name: "Bill Ted's flicks")
List.create(user_id: 4, name: "Great movies")
List.create(user_id: 5, name: "I love movies")
List.create(user_id: 6, name: "Movies i hate?")
List.create(user_id: 7, name: "DVDs and stuff")
List.create(user_id: 8, name: "Well, this is a list")


Movie.create(title: "Mission: Impossible", cast: "Tom Cruise, Jon Voight, Emmanuelle Béart, Henry Czerny", plot: "An American agent, under false suspicion of disloyalty, must discover and expose the real spy without the help of his organization.", year: 1996, metascore: 59, imdb_id: "tt0117060", director: "Brian de Palma")
Movie.create(title: "Michael Clayton", cast: "Tom Wilkinson, George Clooney, Sydney Pollack, Tilda Swinton", plot: "A law firm brings in its \"fixer\" to remedy the situation after a lawyer has a breakdown while representing a chemical company that he knows is guilty in a multibillion-dollar class action suit.", year: 2007, metascore: 82, imdb_id: "tt0465538", director: "Tony Gilroy")
Movie.create(title: "Gremlins 2: The New Batch", cast: "Zach Galligan, Phoebe Cates, John Glover, Robert Prosky", plot: "The Gremlins are back, and this time, they've taken control of a New York City media mogul's high-tech skyscraper.", year: 1990, metascore: 0, imdb_id: "tt0099700", director: "Joe Dante")
Movie.create(title: "Hoop Dreams", cast: "William Gates, Arthur Agee, Emma Gates, Curtis Gates", plot: "A film following the lives of two inner-city Chicago boys who struggle to become college basketball players on the road to going professional.", year: 1994, metascore: 98, imdb_id: "tt0110057", director: "Steve James")
Movie.create(title: "Top Gun", cast: "Tom Cruise, Kelly McGillis, Val Kilmer, Anthony Edwards", plot: "As students at the United States Navy's elite fighter weapons school compete to be best in the class, one daring young pilot learns a few things from a civilian instructor that are not taught in the classroom.", year: 1986, metascore: 50, imdb_id: "tt0092099", director: "Tony Scott")
Movie.create(title: "On the Waterfront", cast: "Marlon Brando, Karl Malden, Lee J. Cobb, Rod Steiger", plot: "An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses.", year: 1954, metascore: 91, imdb_id: "tt0047296", director: "Elia Kazan")
Movie.create(title: "Metropolitan", cast: "Carolyn Farina, Edward Clements, Chris Eigeman, Taylor Nichols", plot: "A group of young upper-class Manhattanites are blithely passing through the gala debutante season, when an unusual outsider joins them and stirs them up.", year: 1990, metascore: 77, imdb_id: "tt0100142", director: "Whit Stillman")

#Movie.create(title: "", cast: "", plot: "", year: , metascore: , imdb_id: "", director: "")

ListsMovies.create(list_id: 1, movie_id: 1)
ListsMovies.create(list_id: 2, movie_id: 1)
ListsMovies.create(list_id: 3, movie_id: 1)
ListsMovies.create(list_id: 4, movie_id: 1)
ListsMovies.create(list_id: 5, movie_id: 1)
ListsMovies.create(list_id: 6, movie_id: 1)
ListsMovies.create(list_id: 7, movie_id: 1)
ListsMovies.create(list_id: 8, movie_id: 1)

ListsMovies.create(list_id: 1, movie_id: 2)
ListsMovies.create(list_id: 2, movie_id: 2)
ListsMovies.create(list_id: 3, movie_id: 2)
ListsMovies.create(list_id: 4, movie_id: 2)
ListsMovies.create(list_id: 5, movie_id: 2)
ListsMovies.create(list_id: 6, movie_id: 2)
ListsMovies.create(list_id: 7, movie_id: 2)

ListsMovies.create(list_id: 1, movie_id: 3)
ListsMovies.create(list_id: 2, movie_id: 3)
ListsMovies.create(list_id: 3, movie_id: 3)
ListsMovies.create(list_id: 4, movie_id: 3)
ListsMovies.create(list_id: 5, movie_id: 3)
ListsMovies.create(list_id: 6, movie_id: 3)

ListsMovies.create(list_id: 1, movie_id: 4)
ListsMovies.create(list_id: 2, movie_id: 4)
ListsMovies.create(list_id: 3, movie_id: 4)
ListsMovies.create(list_id: 4, movie_id: 4)
ListsMovies.create(list_id: 5, movie_id: 4)

ListsMovies.create(list_id: 1, movie_id: 5)
ListsMovies.create(list_id: 2, movie_id: 5)
ListsMovies.create(list_id: 3, movie_id: 5)
ListsMovies.create(list_id: 4, movie_id: 5)

ListsMovies.create(list_id: 1, movie_id: 6)
ListsMovies.create(list_id: 2, movie_id: 6)
ListsMovies.create(list_id: 3, movie_id: 6)